# Generated by Django 5.2.10 on 2026-02-02 12:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Evest', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True, verbose_name='وصف المنصة تحت العنوان')),
                ('license', models.CharField(max_length=100, verbose_name='الترخيص')),
                ('regulator', models.CharField(max_length=100, verbose_name='جهة التنظيم')),
                ('country', models.CharField(max_length=100, verbose_name='بلد التسجيل')),
                ('risk_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان التنبيه')),
                ('risk_message', models.TextField(blank=True, verbose_name='رسالة التحذير')),
                ('risk_link', models.URLField(blank=True, verbose_name='رابط (اقرأ المزيد)')),
                ('is_risk_active', models.BooleanField(default=False, verbose_name='تفعيل التنبيه')),
                ('pros', models.TextField(help_text='أدخل كل ميزة في سطر منفصل', verbose_name='الإيجابيات')),
                ('cons', models.TextField(help_text='أدخل كل عيب في سطر منفصل', verbose_name='السلبيات')),
                ('withdrawal_delay_percent', models.IntegerField(default=0, verbose_name='نسبة تأخر السحب')),
                ('technical_support_percent', models.IntegerField(default=0, verbose_name='نسبة دعم فني')),
                ('slippage_percent', models.IntegerField(default=0, verbose_name='نسبة انزلاقات سعرية')),
                ('website_url', models.URLField(blank=True, verbose_name='رابط الموقع الرسمي')),
                ('is_independent', models.BooleanField(default=True, verbose_name='موقع مستقل وغير تابع')),
            ],
            options={
                'verbose_name': 'بيانات الشركة',
                'verbose_name_plural': 'بيانات الشركة',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم (1-5)')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('country', models.CharField(max_length=100, verbose_name='البلد')),
                ('is_problematic', models.BooleanField(default=False, verbose_name='بلاغ عن مشكلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='review_media/', verbose_name='وسائط المراجعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reviews', to='reviews.users', verbose_name='المستخدم')),
            ],
        ),
    ]
