# Generated by Django 5.2.10 on 2026-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=200, verbose_name='عنوان الميتا')),
                ('meta_description', models.TextField(verbose_name='وصف الميتا')),
            ],
        ),
    ]
