# Generated by Django 5.2.3 on 2026-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'إعدادات الصفحة الرئيسية (SEO & Schema)', 'verbose_name_plural': 'إعدادات الصفحة الرئيسية (SEO & Schema)'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(default=55, help_text='مثال: https://theqa.reviews/', verbose_name='الرابط الأساسي (Canonical URL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النشر الأول'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=models.CharField(default=66, max_length=250, verbose_name='العنوان الرئيسي (Headline)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط انستجرام'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='keywords',
            field=models.TextField(default=565, help_text='كلمات مفصولة بفاصلة', verbose_name='الكلمات المفتاحية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط لينكد إن'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ImageField(default=656, help_text='الصورة التي تظهر عند مشاركة الرابط', upload_to='seo/og/', verbose_name='صورة المشاركة (OG Image)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_type',
            field=models.CharField(default='website', max_length=50, verbose_name='نوع المحتوى (OG Type)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='publisher_address',
            field=models.CharField(default=656859, max_length=255, verbose_name='عنوان الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='publisher_email',
            field=models.EmailField(default=6566, max_length=254, verbose_name='بريد التواصل الرسمي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='publisher_logo',
            field=models.ImageField(default=6565, upload_to='seo/logos/', verbose_name='لوجو الناشر (للسكيما)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='publisher_name',
            field=models.CharField(default=6566, max_length=150, verbose_name='اسم الناشر/الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='publisher_telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_name',
            field=models.CharField(default=9596, max_length=150, verbose_name='اسم الموقع (Schema Name)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تيك توك'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_card',
            field=models.CharField(default='summary_large_image', max_length=50, verbose_name='نوع بطاقة تويتر'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=100, verbose_name='حساب تويتر الموقع (بـ @)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(verbose_name='وصف الميتا (Meta Description)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(max_length=200, verbose_name='عنوان الميتا (Meta Title)'),
        ),
    ]
