# Generated by Django 5.2.3 on 2026-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_homepage_options_homepage_canonical_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='og_type',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publisher_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publisher_email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publisher_logo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='publisher_telephone',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='tiktok_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='twitter_card',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='twitter_site',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='youtube_url',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(verbose_name='وصف الميتا'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_title',
            field=models.CharField(max_length=200, verbose_name='عنوان الميتا'),
        ),
    ]
