# Generated by Django 5.2.10 on 2026-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='user_reviews', to='reviews.review'),
        ),
    ]
