# Generated by Django 5.2.10 on 2026-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_users_mobile_users_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع التجربة')),
            ],
        ),
    ]
