# Generated by Django 5.2.10 on 2026-02-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_typeofexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='experience_type_dynamic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.typeofexperience', verbose_name='نوع التجربة'),
        ),
    ]
